=== pypi-data/pypi-mirror-338/packages/geysergen/geysergen-0.0.2.tar.gz/geysergen-0.0.2/geysergen/schemas/generic.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Verilog Generator Schema",
    "description": "Default Verilog Generator Schema",
    "type": "object",
    "properties": {
        "name": {
            "description": "The name to give the generated python module",
            "type": "string"
        },
        "ip_name": {
            "description": "The verilog name of the module",
            "type": "string"
        },
        "parameters": {
            "description": "The verilog parameters to be passed to this module, a assignment of null requires the user to provide the param. If you wish to include a apostrophe ' in a a string param you must add quotes around your string. Otherwise it will be detected as a sized int like 27'h00.",
            "type": "object",
            "additionalProperties": {
                "type": [
                    "string",
                    "number",
                    "integer",
                    "boolean",
                    "null"
                ]
            },
            "examples":[
                {
                    "PORT_WIDTH":32,
                    "START_COUNT":"27'd0",
                    "PIPELINE_COUNT":null
                }
            ]
        },
        "hidden_parameters": {
            "description": "parameters that should be populated but that shouldn't be exposed in the python module interface",
            "type": "object",
            "additionalProperties": {
                "$comment": "null not allowed since user won't be prompted to populate",
                "type": [
                    "string",
                    "number",
                    "integer",
                    "boolean"
                ]
            },
            "examples":[
                {
                    "PORT_WIDTH":32,
                    "START_COUNT":"27'd0"
                }
            ]
        },
        "interfaces": {
            "description": "Array of dicts representing interfaces",
            "type": "array",
            "items": {
                "type": "object",
                "allOf": [
                    {
                        "properties": {
                            "interface_name": {
                                "description": "The name to give the interface",
                                "type": "string"
                            },
                            "type": {
                                "description": "The type name of the interface",
                                "type": "string"
                            },
                            "side": {
                                "description": "The side of the interface",
                                "type": "string",
                                "enum": [
                                    "source",
                                    "sink",
                                    "start",
                                    "end"
                                ]
                            },
                            "multi": {
                                "description": "List of strings to be substituted for ? in strings used to create the multiple interfaces",
                                "type": "array",
                                "items": {
                                    "type": [
                                        "string",
                                        "integer"
                                    ]
                                }
                            },
                            "multiconnect": {
                                "description": "Behavior if multiple interfaces connected",
                                "type": "string",
                                "enum": [
                                    "false",
                                    "shared",
                                    "interconnect"
                                ]
                            },
                            "interconnect_settings": {
                                "type": "object",
                                "description": "Settings for an interconnect",
                                "properties": {
                                    "params": {
                                        "type": "object",
                                        "description": "All key values will be passed as parameters to the interconnect"
                                    },
                                    "pass_clock": {
                                        "type": "string",
                                        "description": "clock interface to pass to the interconnect. Use the name assigned to the clock in your vgen file"
                                    },
                                    "pass_reset": {
                                        "type": "string",
                                        "description": "reset interface to pass to the interconnect. Use the name assigned to the reset in your vgen file"
                                    }
                                }
                            },
                            "ports": {
                                "type": "object",
                                "description": "Contains ports and their definitions",
                                "additionalProperties": {
                                    "type": "object",
                                    "properties": {
                                        "name": {
                                            "description": "Name of the input/output wire in the module",
                                            "type": "string"
                                        },
                                        "dir": {
                                            "description": "Direction of the wire input/output",
                                            "enum": [
                                                "input",
                                                "output"
                                            ]
                                        },
                                        "width": {
                                            "description": "Size of the port in bits",
                                            "type": "integer",
                                            "minimum": 0
                                        },
                                        "dynamic_width": {
                                            "description": "If specified, the port width will be set by the given param. If started with / the exact command will be pasted allowing for specialized python logic to run in the module. Example '/int(self.parameters_[width]/8)",
                                            "type": "string"
                                        },
                                        "unconnected": {
                                            "description": "Behavior if port isn't connected only applies if input",
                                            "oneOf": [
                                                {
                                                    "description": "Special unconnected port behaviors",
                                                    "enum": [
                                                        "tie_high",
                                                        "tie_low",
                                                        "forbidden",
                                                        "nothing"
                                                    ]
                                                },
                                                {
                                                    "description": "Assign a custom numeric value to a port when it is left unconnected",
                                                    "type": "number"
                                                }
                                            ]
                                        }
                                    },
                                    "required": [
                                        "name"
                                    ],
                                    "$comment": "Don't require direction since it might be placed by the types validator"
                                }
                            }
                        }
                    },
                    {
                        "$ref": "urn:base:special"
                    }
                ],
                "required": [
                    "interface_name",
                    "type",
                    "side",
                    "ports"
                ]
            }
        }
    },
    "required": [
        "name",
        "ip_name",
        "interfaces"
    ]
}

=== pypi-data/pypi-mirror-338/packages/geysergen/geysergen-0.0.2.tar.gz/geysergen-0.0.2/examples/General/noxygen/noxy_combiner.gip.json
{
    "name": "noxy_combiner",
    "ip_name": "noxy_combiner",
    "parameters": {
        "INPUTS":null,
        "DATA_WIDTH":null
    },
    "interfaces": [
        {
            "interface_name": "data_in?",
            "multi": [0,1,2,3,4,5],
            "type": "noxybus",
            "side": "sink",
            "ports": {
                "valid": {
                    "name": "valid_in_bus_?",
                    "dir": "input"
                },
                "ready": {
                    "name": "ready_in_bus_?",
                    "dir": "output"
                }
                ,"data": {
                    "name": "data_in_bus_?",
                    "dir": "input",
                    "dynamic_width": "DATA_WIDTH"
                }
            }
        },
        {
            "interface_name": "data_out",
            "type": "noxybus",
            "side": "source",
            "ports": {
                "valid": {
                    "name": "valid_out_bus",
                    "dir": "output",
                    "dynamic_width": "INPUTS"
                },
                "ready": {
                    "name": "ready_out_bus",
                    "dir": "input",
                    "dynamic_width": "INPUTS"
                }
                ,"data": {
                    "name": "data_out_bus",
                    "dir": "output",
                    "dynamic_width": "/self._parameters['INPUTS']*self._parameters['DATA_WIDTH']"
                }
            }
        }
    ]
}

=== pypi-data/pypi-mirror-338/packages/geysergen/geysergen-0.0.2.tar.gz/geysergen-0.0.2/geysergen/generic_modules/intel/special_mod_json/single_port_sram.vgen.json
{
    "name": "single_port_sram",
    "ip_name": "single_port_sram",
    "parameters":{
        "MEM_BYTES":null,
        "D_WIDTH":null,
        "WORD_ADD":1
    },
    "hidden_parameters":{
       "A_WIDTH":"/int(math.ceil(math.log2(MEM_BYTES))-(0 if WORD_ADD!=1 else math.log2(D_WIDTH/8)))" 
    },
    "interfaces": [
        {
            "interface_name":"clock",
            "side":"sink",
            "type":"clock",
            "ports":{
                "clk":{
                    "name":"clk",
                    "unconnected":"forbidden"
                }
            }
        },
        {
            "interface_name":"reset",
            "side":"sink",
            "type":"reset",
            "ports":{
                "reset":{
                    "name":"reset",
                    "unconnected":"forbidden"
                },
                "reset_req":{
                    "name":"reset_req"
                }
            }
        },
        {
            "interface_name": "ava_memory",
            "side": "sink",
            "type": "avalon",
            "ports": {
                "writedata": {
                    "name": "writedata",
                    "dynamic_width": "D_WIDTH"
                },
                "readdata": {
                    "name": "readdata",
                    "dynamic_width": "D_WIDTH"
                },
                "address": {
                    "name": "address",
                    "dynamic_width": "A_WIDTH"
                },
                "write": {
                    "name": "write"
                },
                "read": {
                    "name": "read"
                },
                "byteenable": {
                    "name": "byteenable",
                    "dynamic_width": "/int(self._parameters['D_WIDTH']/8)"
                }
            }
        }
    ]
}

=== pypi-data/pypi-mirror-338/packages/geysergen/geysergen-0.0.2.tar.gz/geysergen-0.0.2/examples/General/noxygen/top.gip.json
{
    "$schema": "../schemas/vscode.schema.json",
    "name": "noxy_top",
    "ip_name": "noxy_top",
    "parameters": {
        "DATA_WIDTH": null
    },
    "hidden_parameters": {},
    "interfaces": [
        {
            "interface_name": "clock",
            "type": "clock",
            "side": "source",
            "interconnect_settings": {},
            "ports": {
                "clk": {
                    "name": "clk",
                    "dir": "output",
                    "width": 1
                }
            }
        },
        {
            "interface_name": "reset",
            "type": "reset",
            "side": "source",
            "interconnect_settings": {
                "pass_clock": "clock"
            },
            "ports": {
                "reset": {
                    "name": "rst",
                    "dir": "output",
                    "width": 1
                }
            }
        },
        {
            "interface_name": "Node?_in",
            "type": "noxybus",
            "side": "source",
            "multi":["/list(range(0,10000))"],
            "ports": {
                "valid": {
                    "name": "Node?_valid_in",
                    "dir": "output"
                },
                "ready": {
                    "name": "Node?_ready_in",
                    "dir": "input"
                },
                "data": {
                    "name": "Node?_data_in",
                    "dir": "output",
                    "dynamic_width": "DATA_WIDTH"
                }
            }
        },
        {
            "interface_name": "Node?_out",
            "multi": ["/list(range(0,10000))"],
            "type": "noxybus",
            "side": "sink",
            "ports": {
                "valid": {
                    "name": "Node?_valid_out",
                    "dir": "input"
                },
                "ready": {
                    "name": "Node?_ready_out",
                    "dir": "output"
                },
                "data": {
                    "name": "Node?_data_out",
                    "dir": "input",
                    "dynamic_width": "DATA_WIDTH"
                }
            }
        }
    ]
}
